### ISSUE TITLE
Question about airdrop functionality

### ISSUE THREAD

**Issue by boldgate0759** [NFTfi-Genesis/nftfi.eth#2]
Hi, I'm the one who opened [Report 20156](https://bugs.immunefi.com/dashboard/submission/20156) on Immunifi. 
I copy my report on Immunifi below: 
> The pullAirdrop function in AirdropFlashLoan contract is intended to be called by NftfiBundler contract to claim airdrop with a flash loan from NFT boundle owners. However, there is no access control on the pullAirdrop function in AirdropFlashLoan contract. Any malicious user can monitor the mempool and whenever a bundle owner tries to pull airdrop NFTs from AirdropFlashLoan contract, the malicious user can front-run to directly call the pullAirdrop function in AirdropFlashLoan contract to drain the available airdrop tokens without no cost.

I understand that `AirdropFlashLoan` contract is out of scope of the bounty program. It's fine. I am not expecting a bounty or something. 
Just curious, what is the purpose of `pullAirdrop` function in the `NftfiBundler` contract? I didn't find any description of this functionality in the document of NFTfi. 

I understand, airdrop is disabled on the deployed contract on blockchain, so there's no concert at present.
But if the airdrop is enabled some time in the future, do you think the lack of access control in `pullAirdrop` of `AirdropFlashLoan` contract will cause problems? For example, users who try to pull airdrop may suffer from loss of tokens pulled airdrop tokens?

**Comment by infosec-us-team** [comment]
Hello @boldgate0759, 

Users never send their NFTs directly to the `AirdropFlashLoan` smart contract, it doesn't matter if the attacker sees a call to `pullAirdrop(...)` in the mempool because the `AirdropFlashLoan` smart contract is always fully empty. It contains no NFTs and no airdropped ERC20 tokens.

Here's a simplified version of the purpose of `pullAirdrop(...)` in the `NftfiBundler` contract:

**[Step 1-]** The owner of the `NftfiBundler` or `ImmutableBundle` calls `pullAirdrop(...)`

**[Step 2-]** The `NftfiBundler` or `ImmutableBundle` sends the NFT to the `AirdropFlashLoan` smart contract

**[Step 3-]** The `AirdropFlashLoan` smart contract calls the whitelisted airdrop to claim the ERC20 tokens

**[Step 4-]** The `AirdropFlashLoan` smart contract sends the claimed tokens (if any) to the owner of the  `NftfiBundler` or `ImmutableBundle`.

**[Step 5-]** The `NftfiBundler` or `ImmutableBundle` makes sure to get back the NFT from the `AirdropFlashLoan` before the transaction ends.

Steps 1, 2, 3, 4, and 5 happen atomically (within 1 transaction). Before this transaction is executed (only exists in the mempool) the `AirdropFlashLoan` is empty, and after the transaction is executed, the `AirdropFlashLoan` will be empty as well.

Front-running this will revert at #L55 (https://github.com/NFTfi-Genesis/nftfi.eth/blob/main/V2/contracts/airdrop/AirdropFlashLoan.sol#L55) when the `_target` smart contract checks if `AirdropFlashLoan` owns the NFT of the airdrop.

If you have more questions, do not hesitate to ask.

> Note: Fortunately, this was just a misunderstanding, but be careful next time about public disclosure of information reported via Immunefi without protocol consent.

**Comment by boldgate0759** [comment]
Thanks for your explanation. I apology that I disclose the immunefi info. I thought the issue on Immunefi was closed so it is OK to ask on GitHub. I still have some questions. I will send you via email.

**Comment by boldgate0759** [comment]
@infosec-us-team Do you have an email address for me to ask or some private discord channel?

**Comment by uroboros** [comment]
thanks @infosec-us-team for fielding this question 🙏

**Comment by Troublor** [comment]
@uroboros I still have a few follow up questions. Would you mind if I directly send emails to you?

**Comment by boldgate0759** [comment]
@uroboros I still have a few follow up questions. Would you mind if I directly send emails to you?
